### ISSUE TITLE
バグ :  『Full Material Card』からスポーンしたEntityの挙動がおかしい

### ISSUE THREAD

**Issue by Schr0** [Schr0/Schr0sMaterialScan#1]
# 具体的な内容
- 『Full Material Card』からスポーンしたEntityの挙動がカクついたものとなり、通常の挙動ではないものとなる。
- リログをすると以上の挙動が解消される。

# 考えられる原因
- 『リログをすると解消する』という点から、スポーン時にサーバーとクライアントの同期が成されていないのではないか？

**Comment by flammpfeil** [comment]
ItemMaterialCard.spawnContentEntityInWorld
setPositionAndUpdate後に
livingBase.motionY = livingBase.motionX = livingBase.motionZ = 0;
とかでどうです。

**Comment by Schr0** [comment]
回答していただき、ありがとうございます。

> ItemMaterialCard.spawnContentEntityInWorld
> setPositionAndUpdate後に
> livingBase.motionY = livingBase.motionX = livingBase.motionZ = 0;

以上の処理を試してみたところ、カクつきが解消され通常の挙動をしてくれるようになりました。

早速、修正したverをコミットしたいと思います。

分り易いご指摘、ありがとうございました。
