### ISSUE TITLE
バグ :  Gui上に正しくEntityが描画されない

### ISSUE THREAD

**Issue by Schr0** [Schr0/Schr0sMaterialScan#2]
# 具体的な内容
 『Material Book』を用いて表示されるGuiにおいて、『Full Material Card』で捕えた一部のEntityが表示されない

- バニラにおいて
『装飾品（鞍・装備）を付けた馬』の『装飾品』のみが表示されない。

- 他mod導入時において
一部のEntityは、影だけが映っている状態で透明な状態となる。

# 考えられる原因
- NBTの同期の問題？
- 実際にWorldにスポーンした時に描画処理が成されているため？

**Comment by flammpfeil** [comment]
ContainerMaterialBook.bookInventory.markDirty()中で
ContainerMaterialBook.this.setCardEntityにセットするEntityの取得時

EntityLivingBase entity = null;
boolean tmp = world.isRemote;
try{
　world.isRemote = false;
　entity = itemCard.getContentEntity(stackCard, world);
}catch(Throwable e){
　world.isRemote = tmp;
　entity = itemCard.getContentEntity(stackCard, world);
}finally{
 world.isRemote = tmp;
}
ContainerMaterialBook.this.setCardEntity(world, entity);

のように、一次的にサーバ側であると誤認させて生成することで、NBTからのEntityの全データ再生ができるかとおもいます。
ただ、誤認させているだけですので、クラッシュの危険性は高いため確実に例外処理は必要かとおもいます。

**Comment by Schr0** [comment]
回答していただき、ありがとうございます。

> ContainerMaterialBook.bookInventory.markDirty()中で
> ContainerMaterialBook.this.setCardEntityにセットするEntityの取得時
> 
> EntityLivingBase entity = null;
> boolean tmp = world.isRemote;
> try{
> 　world.isRemote = false;
> 　entity = itemCard.getContentEntity(stackCard, world);
> }catch(Throwable e){
> 　world.isRemote = tmp;
> 　entity = itemCard.getContentEntity(stackCard, world);
> }finally{
> world.isRemote = tmp;
> }
> ContainerMaterialBook.this.setCardEntity(world, entity);

以上の処理を組み込んだ所、今まで正しく表示されていなかったEntityも表示されるようになりました！！！

長い間悩んでいたので、解決できて本当に嬉しいです・・・ありがとうございました。

#1 に引き続き、分り易いご指摘ありがとうございました。
